spring:
  datasource:
    #这里填写里的数据库路径
    url:
    #这里填写你的数据库用户名
    username:
    #这里填写你的数据库密码
    password:
    #这里填写你的数据库驱动  MySQL5是：com.mysql.jdbc.Driver    MySQL8是：com.mysql.cj.jdbc.Driver
    driver-class-name:

    druid:
      aop-patterns: com.dlhjw.website.*  #springbean监控
      filters: stat,wall,slf4j  #所有开启的功能

      stat-view-servlet:  #监控页配置
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter:  #web监控
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      filter:
        stat: #sql监控
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall: #防火墙
          enabled: true
          config:
            drop-table-allow: false

  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html


  #开启rest风格
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 这里可以配置您的端口信息
server:
  port: 8087
